### ISSUE TITLE
Review of precision

### ISSUE THREAD

**Issue by jakwisn** [DeepPoolAI/DeepPoolAI#13]
The precision metric is very important to us. It should be reviewed by randomly selecting a few areas in different cities and checking which detected pools are actually pools.

**Comment by Szwagi3r** [comment]
Algorithm's output was tested on 790 observations. 539 of them were correctly recognised by as pools, 39 places were incorrectly recognised as pools. Model missed 212 pools. Statistics for model are as shown below:
Precision: 0.93, 
Recall: 0.72,
which meets our criteria.
