### ISSUE TITLE
Covering a terrain with photos

### ISSUE THREAD

**Issue by jakwisn** [DeepPoolAI/DeepPoolAI#9]
The terrain should be covered (for example district, city) with photos. They should make a grid of some kind. The overlap between photos should be as little as possible.

**Comment by HaZdula** [comment]
Might be useful: https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system

**Comment by jakwisn** [comment]
Imo it will be better to encapsulate grid in other Object
